name: BaDuaCoverage
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Clone and build Ba-Dua repository
        run: |
          git clone https://github.com/saeg/ba-dua
          cd ba-dua
          git checkout d2401f0
          mvn clean install
          cd ..

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean verify -P Ba-Dua

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: BaDuaReport
          path: openjpa-kernel/target/badua.xml
          if-no-files-found: error
